/*
 * 
 *           ______ _______ _    _ ______ _____  _____  _____ 
 *     /\   |  ____|__   __| |  | |  ____|  __ \|_   _|/ ____|
 *    /  \  | |__     | |  | |__| | |__  | |__) | | | | (___  
 *   / /\ \ |  __|    | |  |  __  |  __| |  _  /  | | |  \___ \ 
 *  / ____ \| |____   | |  |  |  | | |____| | \ \ _| |_ ____) |
 * /_/    \_\______|  |_|  |_|  |_|______|_|  \_\_____|_____/ 
 * 
 *                                                                                     v1.0
 * @name Aetheris
 *
 * @author dkitagawa
 *
 * @file ae_mt64.h
 *
 * @brief MT19937-64 pseudorandom number generator state and methods.
 *
 * @copyright (c) 2026 Douglas Kitagawa
 *
 */

#ifndef AE_MT64_H
#define AE_MT64_H

#include <aetheris/ae_error.h>
#include <aetheris/ae_types.h>

/* ============================================================ */

/*
 * MT19937-64 as specified by the reference implementation: a 64-bit
 * Mersenne Twister with a state vector of N words. One instance keeps
 * its own state; the same instance can be reseeded at any time.
 * Instances are not thread-safe; callers must serialize access.
 *
 * The default constructor state is generated by seeding from 5489U,
 * matching the convention used by existing call sites.
 */

#define AE_MT64_N 312
#define AE_MT64_M 156

/* State vector words; N = 312. */
typedef struct ae_mt64 {
    ae_u64 mt[AE_MT64_N];
    ae_s32 mti; /* MT64_N + 1 means mt[] is not initialized. */
} ae_mt64_t;

/**
 * ae_mt64_init - initialize an MT19937-64 generator.
 * @mt: generator to initialize.
 * @seed: 64-bit seed value.
 *
 * The generator must not be used after init returns with a failure.
 * Returns AE_OK on success.
 */
ae_error_t ae_mt64_init(ae_mt64_t *mt, ae_u64 seed);

/**
 * ae_mt64_set_seed - reseed a generator.
 * @mt: generator to reseed.
 * @seed: 64-bit seed value.
 *
 * Reinitializes the state vector from seed. Safe to call at any time.
 */
void ae_mt64_set_seed(ae_mt64_t *mt, ae_u64 seed);

/**
 * ae_mt64_next - return the next 64-bit value.
 * @mt: generator to draw from.
 *
 * Generates N words at a time when the current batch is exhausted.
 * Returns the next pseudo-random value.
 */
ae_u64 ae_mt64_next(ae_mt64_t *mt);

/* ============================================================ */

#endif /* AE_MT64_H */